<a href="https://colab.research.google.com/github/Mumenunnessa/Hello-world/blob/master/AI_Lab.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [43]:
import numpy as np

In [44]:
L = list(range(10))

In [45]:
L

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [46]:
[str(c) for c in L]

['0', '1', '2', '3', '4', '5', '6', '7', '8', '9']

In [47]:
[type(item) for item in L]

[int, int, int, int, int, int, int, int, int, int]

In [48]:
np.zeros(10, dtype='float')

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [49]:
np.ones((3,5) , dtype='float')

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [50]:
np.arange(0, 30, 3)

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [51]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [52]:
x1 = np.array([[4, 3, 5, 7, 8], 
              [5, 6, 7, 9, 0]])
x1

array([[4, 3, 5, 7, 8],
       [5, 6, 7, 9, 0]])

In [53]:
#x1[2]

In [54]:
#x1[-1]

In [55]:
#x1[-3]

In [56]:
x1[0,2]

5

In [60]:
x = np.arange(10)

In [61]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [62]:
x[:7]

array([0, 1, 2, 3, 4, 5, 6])

In [63]:
x[4:]

array([4, 5, 6, 7, 8, 9])

In [64]:
x[2:5]

array([2, 3, 4])

In [66]:
x[::2]

array([0, 2, 4, 6, 8])

In [67]:
x[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [68]:
a = np.array([1, 2, 3])
b = np.array([2, 7, 0])
c = np.array([6, 2, 5])

In [69]:
np.concatenate([a, b, c])

array([1, 2, 3, 2, 7, 0, 6, 2, 5])

Pandas


In [70]:
import pandas as pd

In [71]:
data = {
    'apple': [3, 2, 0, 1],
    'orange': [5, 8, 9, 0]    
}

In [72]:
purchase = pd.DataFrame(data)

In [73]:
purchase

apple  orange
0      3       5
1      2       8
2      0       9
3      1       0

In [74]:
purchase = pd.DataFrame(data, index=['A', 'E', 'I', 'O'])

In [75]:
purchase

apple  orange
A      3       5
E      2       8
I      0       9
O      1       0

In [76]:
data = pd.DataFrame({'country':['Bangladesh', 'India', 'Japan', 'Chile'],
                     'Rank': [121, 60, 50, 40 ]
                     })

In [77]:
data

country  Rank
0  Bangladesh   121
1       India    60
2       Japan    50
3       Chile    40

In [78]:
data.describe()

Rank
count    4.000000
mean    67.750000
std     36.426867
min     40.000000
25%     47.500000
50%     55.000000
75%     75.250000
max    121.000000

In [79]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 2 columns):
 #   Column   Non-Null Count  Dtype 
---  ------   --------------  ----- 
 0   country  4 non-null      object
 1   Rank     4 non-null      int64 
dtypes: int64(1), object(1)
memory usage: 192.0+ bytes


In [81]:
import pandas as pd
df = pd.read_csv("/content/drive/MyDrive/Personal things (important)/iris_csv.csv")

In [82]:
df

sepallength  sepalwidth  petallength  petalwidth           class
0            5.1         3.5          1.4         0.2     Iris-setosa
1            4.9         3.0          1.4         0.2     Iris-setosa
2            4.7         3.2          1.3         0.2     Iris-setosa
3            4.6         3.1          1.5         0.2     Iris-setosa
4            5.0         3.6          1.4         0.2     Iris-setosa
..           ...         ...          ...         ...             ...
145          6.7         3.0          5.2         2.3  Iris-virginica
146          6.3         2.5          5.0         1.9  Iris-virginica
147          6.5         3.0          5.2         2.0  Iris-virginica
148          6.2         3.4          5.4         2.3  Iris-virginica
149          5.9         3.0          5.1         1.8  Iris-virginica

[150 rows x 5 columns]

In [85]:
df.head()

sepallength  sepalwidth  petallength  petalwidth        class
0          5.1         3.5          1.4         0.2  Iris-setosa
1          4.9         3.0          1.4         0.2  Iris-setosa
2          4.7         3.2          1.3         0.2  Iris-setosa
3          4.6         3.1          1.5         0.2  Iris-setosa
4          5.0         3.6          1.4         0.2  Iris-setosa

In [84]:
df.head(10)

sepallength  sepalwidth  petallength  petalwidth        class
0          5.1         3.5          1.4         0.2  Iris-setosa
1          4.9         3.0          1.4         0.2  Iris-setosa
2          4.7         3.2          1.3         0.2  Iris-setosa
3          4.6         3.1          1.5         0.2  Iris-setosa
4          5.0         3.6          1.4         0.2  Iris-setosa
5          5.4         3.9          1.7         0.4  Iris-setosa
6          4.6         3.4          1.4         0.3  Iris-setosa
7          5.0         3.4          1.5         0.2  Iris-setosa
8          4.4         2.9          1.4         0.2  Iris-setosa
9          4.9         3.1          1.5         0.1  Iris-setosa

In [86]:
df.columns

Index(['sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'class'], dtype='object')

In [87]:
df.shape

(150, 5)

In [88]:
df.tail()

sepallength  sepalwidth  petallength  petalwidth           class
145          6.7         3.0          5.2         2.3  Iris-virginica
146          6.3         2.5          5.0         1.9  Iris-virginica
147          6.5         3.0          5.2         2.0  Iris-virginica
148          6.2         3.4          5.4         2.3  Iris-virginica
149          5.9         3.0          5.1         1.8  Iris-virginica

In [90]:
print(df[10:21])

    sepallength  sepalwidth  petallength  petalwidth        class
10          5.4         3.7          1.5         0.2  Iris-setosa
11          4.8         3.4          1.6         0.2  Iris-setosa
12          4.8         3.0          1.4         0.1  Iris-setosa
13          4.3         3.0          1.1         0.1  Iris-setosa
14          5.8         4.0          1.2         0.2  Iris-setosa
15          5.7         4.4          1.5         0.4  Iris-setosa
16          5.4         3.9          1.3         0.4  Iris-setosa
17          5.1         3.5          1.4         0.3  Iris-setosa
18          5.7         3.8          1.7         0.3  Iris-setosa
19          5.1         3.8          1.5         0.3  Iris-setosa
20          5.4         3.4          1.7         0.2  Iris-setosa
