<a href="https://colab.research.google.com/github/Mumenunnessa/Hello-world/blob/master/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [30]:
import numpy as np

In [31]:
L = list(range(10))

In [32]:
print(L)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


In [33]:
[str(c) for c in L]     #convert strng to integer-list comprehension

['0', '1', '2', '3', '4', '5', '6', '7', '8', '9']

In [34]:
[type(item) for item in L]

[int, int, int, int, int, int, int, int, int, int]

Creating Array

In [35]:
import pandas as pd
data = {
    'apples': [3, 2, 0, 1], 
    'oranges': [0, 3, 7, 2]
}

In [36]:
purchases = pd.DataFrame(data)
purchases

apples  oranges
0       3        0
1       2        3
2       0        7
3       1        2

In [37]:
x1 = np.array([4, 3, 4, 4, 8, 4])

In [38]:
x1

array([4, 3, 4, 4, 8, 4])

In [39]:
x1[2]     #index

4

In [40]:
x1[-1]       #get the last value

4

In [41]:
np.zeros(10, dtype='int')

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [43]:
#creating a 3 row x 5 column matrix
np.ones((3,5), dtype=float)


array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [45]:
#creating a matrix with a predefined value
np.full((3,5),1.23)

array([[1.23, 1.23, 1.23, 1.23, 1.23],
       [1.23, 1.23, 1.23, 1.23, 1.23],
       [1.23, 1.23, 1.23, 1.23, 1.23]])

In [46]:
#create an array with a set sequence
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])